# Generated by Django 3.2.4 on 2021-07-04 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.TextField(blank=True, max_length=500, null=True)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_discount_price', models.FloatField(blank=True, null=True)),
                ('product_quantity_type', models.CharField(choices=[('250GM', '250 Grams'), ('500GM', '500 Grams'), ('750GM', '750 Grams'), ('1000GM', '1000 Grams'), ('1PC', '1 Pc'), ('12PC', '12 Pc')], max_length=6)),
                ('product_type', models.CharField(choices=[('V', 'Vegetables'), ('F', 'Fruits')], max_length=1)),
                ('product_quantity', models.IntegerField()),
                ('product_photo', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_created_date', models.DateTimeField(auto_now_add=True)),
                ('wishlist_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('wishlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
